name: cbill
description: "A new Flutter project."
publish_to: "none"
version: 0.2.1+1

environment:
  sdk: ^3.5.4

dependencies:
  barcode_widget: ^2.0.4
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # example:
  fonts:
    - family: Lufga
      fonts:
        - asset: fonts/Lufga.ttf
